apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name:  serviceservice
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.2.3
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:8080"]
        readinesProbe:
          initialDelayseconds: 5 
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:8080"]
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: emailservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: service
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.3
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:8080"]
        readinesProbe:
          initialDelayseconds: 5
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:8080"]
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"

        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"

---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  selector:
    app.kubernetes.io/name: recommendationservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: service
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.2.3
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:3550"]
        readinesProbe:
          initialDelayseconds: 5
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:3550"]
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  selector:
    app.kubernetes.io/name: productcatalogservice
  ports:
    - protocol: TCP
      port: 3550
      targetPort: 3550

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: service
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.2.3
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:50051"]
        readinesProbe:
          initialDelayseconds: 5
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:50051"]
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  selector:
    app.kubernetes.io/name: paymentservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: service
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.3
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:50051"]
        readinesProbe:
          initialDelayseconds: 5
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:50051"]
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  selector:
    app.kubernetes.io/name: shippingservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:  
    app: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: service
        image: gcr.io/google-samples/microservices-demo/adservice:v0.2.3
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:9555"]
        readinesProbe:
          initialDelayseconds: 5
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:9555"]
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  selector:
    app.kubernetes.io/name: adservice
  ports:
    - protocol: TCP
      port: 9555
      targetPort: 9555

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels: 
    app: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name:  service
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.3
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:5050"]
        readinesProbe:
          initialDelayseconds: 5
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:5050"]
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "8080"

        - name: EMAIL_SERVICE_ADDR
          value: "emailservice:8080"

        - name: PAYMENT_SERVICE_ADDR
          value: "paymentservice:50051"

        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
      
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"

        - name: PRODUCT_CATALOG_ADDR
          value: "productcatalog:3550"

        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
     
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  selector:
    app.kubernetes.io/name: checkoutservice
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name:  service
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.2.3
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:7000"]
        readinesProbe:
          initialDelayseconds: 5
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:7000"]        
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  selector:
    app.kubernetes.io/name: currencyservice
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name:  service
        image: gcr.io/google-samples/microservices-demo/cartservice:v0.2.3
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:7070"]
        readinesProbe:
          initialDelayseconds: 5
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:7070"]
        ports:
        - containerPort: 7070
        env:
        - name: PORT
          value: "7070"
        - name: REDIS-CART
          value: "redis-cart:6379"

---
apiVersion: v1
kind: Service
metadata: 
  name: cartservice
spec:
  selector:
    app.kubernetes.io/name: cartservice
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name:  redis
        image: redis:alpine
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:6379"]
        readinesProbe:
          initialDelayseconds: 5
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:6379"]
        volumeMounts: 
        - name: redis-data
          mountPath: /data
        ports:
        - containerPort: 6379
      volumes:
      - name: redis-data
        emptyDir: {} 

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  selector:
    app.kubernetes.io/name: redis-cart
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name:  service
        image: gcr.io/google-samples/microservices-demo/frontend:v0.2.3
        livenessProbe:
          InitialDelaySeconds: 5
          periodSeconds: 5 
          exec: 
            command: ["/bin/grpc_health", "-addr=:8080"]
        readinesProbe:
          initialDelayseconds: 5
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health", "-addr=:8080"]
        ports:
        - containerPort: 8080
        
        env:
        - name: PORT
          value: "8080"

        - name: AD_SERVICE_ADDR
          value: "adservice:9555"

        - name: PRODUCT_CATALOG_ADDR
          value: "productcatalog:3550"

        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
      
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"

        - name: PRODUCT_CATALOG_ADDR
          value: "productcatalog:3550"

        - name: CART_SERVICE_ADDR
          value: "cartservice:7070" 

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: Loadbalancer

  selector:
    app.kubernetes.io/name: 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      

