appName: emailservice
appTag: v0.2.3
appImage: gcr.io/google-samples/microservices-demo/emailservice
appReplica: 1
containerName: service
containerPort: 8080
containerEnvVars: 
- name: PORT
  value: "8080"

serviceType: ClusterIP
servicePort: 8080
 