appName: recommendationservice
appTag: v0.2.3
appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appReplica: 1
containerName: service
containerPort: 8080
containerEnvVars: 
- name: PORT
  value: "8080"

- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"


serviceType: ClusterIP
servicePort: 8080
