appName: frontend
appTag: v0.2.3
appImage: gcr.io/google-samples/microservices-demo/frontend
appReplica: 1
containerName: service
containerPort: 8080

containerEnvVars: 
- name: PORT
  value: "8080"

- name: AD_SERVICE_ADDR
  Evalue: "adservice:9555"

- name: PRODUCT_CATALOG_ADDR
  value: "productcatalog:3550"

- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"

- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"

- name: PRODUCT_CATALOG_ADDR
  value: "productcatalog:3550"

- name: CART_SERVICE_ADDR
  value: "cartservice:7070" 



 

serviceType: LoadBalancer
servicePort: 80